# BlockParty configuration

LocaleFileName: locale_en.yml
SaveOnDisable: false

BungeeCord:
  Enabled: False
  DefaultArena: Arena

MusicServer:
  Enabled: False
  WebSocketLibrary: jetty
  Port: 8080

Database:
  #Use "MySQL" to enable MySQL
  Method: SQL
  TablePrefix: "bp_"

  SQLOptions:
    FileName: "database.db"

  MySQLOptions:
    Host: localhost
    Port: 3306
    Database: database
    Username: username
    Password: password
