name: BlockParty
version: 2.0.2
authors: [Leon167, pauhull]
description: Official BlockParty Plugin
main: de.leonkoth.blockparty.Main
softdepend: [Multiverse-Core, MCJukebox, NoteBlockAPI]

commands:
  blockparty:
    aliases: [bp, bparty]
    description: Get information on how to use this Plugin
    usage: /blockparty to get more information

api-version: 1.13